# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: MongoDB.MongoDBAtlasCLI
PackageVersion: 1.5.1
PackageLocale: en-US
Publisher: MongoDB, Inc.
PublisherUrl: https://www.mongodb.com/
PublisherSupportUrl: https://github.com/mongodb/mongodb-atlas-cli/issues
PrivacyUrl: https://www.mongodb.com/legal/privacy-policy
PackageName: MongoDB Atlas CLI
PackageUrl: https://www.mongodb.com/docs/atlas/cli/stable/
License: Apache-2.0
ShortDescription: The Atlas CLI (mongodb-atlas-cli) lets you manage your MongoDB Atlas deployments from the command line.
Moniker: mongodb-atlas-cli
Tags:
- atlas
- cli
- cloud
- cloud-management
- database
- mongodb
ReleaseNotesUrl: https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-changelog/
Documentations:
- DocumentLabel: Command Reference
  DocumentUrl: https://www.mongodb.com/docs/atlas/cli/stable/command/atlas/
- DocumentLabel: Tutorials
  DocumentUrl: https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-tutorials/
ManifestType: defaultLocale
ManifestVersion: 1.4.0
